[server_configure]
server_addr = ":8080"

[baidu_map_configure]
## 百度Map AK
ak = ""

[mysql_configure]
driver = "mysql"
## 账号
user_name = ""
## 密码
pw = ""
host = "127.0.0.1"
port = "3306"
dbname = "imaotai"
timeout = "10s"

[log_configure]
log_file_path = "../log/"
log_file_name = "system.log"
